#!/bin/bash
# Manage a paired bluetooth device, via bluetoothctl
# NOTE: DOESN'T WORK ANYMORE, bluetoothctl cmd doesn't terminate anymore 

# How to pair a new device:
# 1. bluetoothctl
# 2. power on
# 3. scan on
# 4. pair 
# 5. trust device

# Wireless devices
declare -A devices
# for taotronics, connecting to "L" should connect both earbuds
devices[ttl]="TAOTRONICS SoundLiberty 95 L"
devices[ttr]="TAOTRONICS SoundLiberty 95 R"
# PrimeCables CSBT-322 Wireless Speaker
devices[spkr]="CSBT-322"
devices[default]="${devices[ttl]}"

# optional: connect / disconnect (default: connect)
# optional: device name (default: use devices[default])
[[ -z "$1" ]] && CMD="c" || CMD="$1"

if [[ -z "$2" ]]; then
    TARGET="${devices[default]}"
else
    for i in "${!devices[@]}"
    do
        if [[ "$i" == "$2" ]]; then
            TARGET="${devices[$i]}"
            break
        fi
    done
    if [[ -z "$TARGET" ]]; then
        echo "Device $2 not found"
        exit 1
    fi
fi
echo "Target: $TARGET"

MAC_ADDR=$(bluetoothctl devices | awk -F'\t' -v output="$TARGET" 'BEGIN {OFS = FS} $1 ~ output { print $1 }' | awk '{print $2}')
echo "Mac Addr: $MAC_ADDR"

case $CMD in
    "c")
        echo "Connecting..."
        bluetoothctl connect "$MAC_ADDR"
        ;;
    "dc")
        echo "Disconnecting..."
        bluetoothctl disconnect "$MAC_ADDR"
        ;;
    *)
        echo "provide: (c/dc) [dev]"
        ;;
esac

    

