#!/bin/bash
# Virtscreen management (for extending screen to an ipad)
# https://github.com/kbumsik/VirtScreen

if [[ -z "$1" ]]; then
    echo "Provide: (start/stop/status/toggle)"
    exit 1
fi

VS_SESSION_NAME="virtscreen"

case $1 in
    start)
        # only launch if not already running
        if tmux has-session -t $VS_SESSION_NAME 2>/dev/null; then
            echo "Virtscreen already running"
            exit 0
        fi
        
        # start virtscreen in a new tmux session
        tmux new-session -d -s $VS_SESSION_NAME 'virtscreen --left'

        # wait until x11vnc is launched
        while sleep 1; do
            if (pgrep -x "x11vnc" 1>/dev/null); then
                break
            fi
            notify-send -t 1000 "VIRTSCREEN" "Waiting for virtscreen to launch..."
        done

        # move workspace 5 over
        i3-msg "workspace 5; move workspace to output left"

        # re-rotate bg
        bg-rotate
        ;;
    kill)
        tmux kill-session -t "$VS_SESSION_NAME"
        bg-rotate
        ;;
    *)
        echo "Unrecognized option $1"
        exit 1
        ;;
esac