#!/bin/bash
# restart compositor (compton)

CURR="$(dirname "$(realpath "$0")")"
DETACH="$CURR/detach"
CONF="$(dirname "$CURR")/term/compton.conf"

killall -q compton
"$DETACH" compton --config "$CONF"