#!/bin/bash
# must run from sdmain root 
# After building on Dev VM, copy the generated intellij deps to local sdmain 
# ex: "copy-intellij-deps 10.0.00.00"

if [[ -z "$1" ]]; then
    echo "provide remote ip address"
    exit 1
fi

if [[ "$(basename "$PWD")" != "sdmain" ]]; then
    echo "must run within sdmain root"
    exit 1
fi

REMOTE="$1"
target="src/java/sd/target"

scp ubuntu@"$REMOTE":~/sdmain/$target/conscrypt/conscrypt.jar conscrypt.jar
rm -rf $target/conscrypt/conscrypt.jar
mv conscrypt.jar $target/conscrypt/conscrypt.jar
echo "Copied conscrypt"

scp ubuntu@"$REMOTE":~/sdmain/$target/intellij-deps/generated-intellij-deps.jar generated-intellij-deps.jar
rm -rf $target/intellij-deps/generated-intellij-deps.jar
mv generated-intellij-deps.jar $target/intellij-deps/generated-intellij-deps.jar
echo "Copied generated-intellij-deps"