#!/bin/bash
# Run a process in the background

# at least 1 argument to detach should exist
if [[ $# -lt 1 ]]; then
    echo "Provide a (process) to run in bg"
    exit 1
fi

# the first argument should be a valid executable
if ! command -v "$1" &> /dev/null; then
    echo "Provided process does not exist"
    exit 1
fi

# pass all arguments from detach to nohup
# ignore log file, stdout and stderr
CMD="${*:1}"
nohup "$($CMD)" >/dev/null 2>&1 &

# wait for process to exit, if faulty
sleep 1

# check if the process is still running
kill -0 "$!" >/dev/null 2>&1
if [[ "$?" -eq 1 ]]; then
    echo "Failed to run command"
    exit 1
fi

# return PID of bg process
echo "Running '$CMD' in bg, PID: $!"
