#!/bin/bash
# Open a file copied to clipboard in an editor

OPATH=$(xclip -o)

# notifications
NTF_NAME="Open in Editor"
NTF_TIME="5000"

# Directories to search
declare -A dirs
dirs[home]=""
dirs[master]="$HOME/sdmain/"
dirs[master2]="$HOME/master-2/sdmain/"
dirs[b52]="$HOME/b52/sdmain/"
dirs[b53]="$HOME/b53/sdmain/"
dirs[default]="${dirs[master]}"

# .scala -> open in idea
# else -> open in vscode
open_file () {
    if [[ "$1" == *.scala ]]; then
        idea "$1"
    else
        code "$1"
    fi
}

# just open in vscode
open_dir () {
    code "$1"
}

case $1 in
    0) DIR="${dirs[home]}";;
    m1) DIR="${dirs[master]}";;
    m2) DIR="${dirs[master2]}";;
    b52) DIR="${dirs[b52]}";;
    b53) DIR="${dirs[b53]}";;
    *) notify-send -t $NTF_TIME "$NTF_NAME" \ "Invalid Workspace";;
esac


# resolve tilde
eval OPATH="$OPATH"
# remove leading slash, if exists
OPATH="${OPATH#/}"

# path outside of sdmain
if [[ -f "$OPATH" || -d "$OPATH" ]]; then
    FULL_PATH="$OPATH"
# path within sdmain
elif [[ -f "$DIR/$OPATH" || -d "$DIR/$OPATH" ]]; then
    FULL_PATH="$DIR/$OPATH"
else
    notify-send -t $NTF_TIME "$NTF_NAME" \ "DIR: $1\n Invalid Path: $OPATH"
    exit 1
fi

notify-send -t $NTF_TIME "$NTF_NAME" \ "DIR: $1\n Path: $FULL_PATH"
open_file "$FULL_PATH"