#!/bin/bash
# Connect to an already paired bluetooth device, via bluetoothctl

# Pair new device:
# 1. bluetoothctl
# 2. power on
# 3. scan on
# 4. pair 

# Wireless devices
declare -A devices
devices[taotronics]="TAOTRONICS SoundLiberty 95 L"
devices[default]="${devices[taotronics]}"

if [[ -z "$1" ]]; then
    TARGET="${devices[default]}"
else
    for i in "${!devices[@]}"
    do
        if [[ "$i" == "$1" ]]; then
            TARGET="${devices[$i]}"
            break
        fi
    done
fi

echo "Connecting to $TARGET"
MAC_ADDR=$(bluetoothctl devices | awk -F'\t' -v output="$TARGET" 'BEGIN {OFS = FS} $1 ~ output { print $1 }' | awk '{print $2}')
bluetoothctl connect "$MAC_ADDR"