#!/bin/bash
# Launch sd_dev_box inside named tmux instances

declare -A workspaces
workspaces[m1]="$HOME/sdmain"
workspaces[m2]="$HOME/master-2/sdmain"
workspaces[m3]="$HOME/master-3/sdmain"
workspaces[b52]="$HOME/b52/sdmain"
workspaces[b53]="$HOME/b53/sdmain"

function is_running () {
    (tmux has-session -t "$1" 2>/dev/null) && return 0 || return 1
}

function is_valid_ws () {
    for i in "${!workspaces[@]}"
    do
        if [[ "$i" == "$1" ]]; then
            return 0
        fi
    done
    return 1
}

function print_help () {
    STR="provide: ("
    for i in "${!workspaces[@]}"
    do
        STR="$STR $i "
    done
    STR="$STR)"
    echo "$STR"
}

if (! is_valid_ws "$1"); then
    print_help
    exit 1
fi

if (is_running "$1"); then
    echo "tmux session $1 already running"
    tmux attach -t "$1"
    exit 0
fi

echo "running $1"
tmux new-session -d -s "$1" "sd_dev_box --sdmain_repo ${workspaces[$1]}"
tmux attach -t "$1"